### ISSUE TITLE
Error importing csv.

### ISSUE THREAD

**Issue by RyuuSlayer** [h-quer/Slaanesh#36]
[gamelist.csv](https://github.com/h-quer/Slaanesh/files/14857596/gamelist.csv)
[playthroughs.csv](https://github.com/h-quer/Slaanesh/files/14857597/playthroughs.csv)
<img width="501" alt="image" src="https://github.com/h-quer/Slaanesh/assets/33106127/0b8be7f6-bee1-4b03-9c05-c795c0fb6b49">

**Comment by h-quer** [comment]
So far, I haven't been able to replicate this on my end. Exporting, clearing the database, and then importing works fine here. csv files do look fine, though. It seems like somehow it's trying to read a timestamp as string.
Are you running the newest version? And the csv files themselves are simply the output of the csv export, right?

**Comment by RyuuSlayer** [comment]
Yeah newest version, to make sure i deleted the database file manually. On first import i get this: 
<img width="559" alt="image" src="https://github.com/h-quer/Slaanesh/assets/33106127/57c05c81-d054-465d-b4e8-a74bbfb40563">
When i try to click import again it tells me the games are in the database, but i cannot see them, neither after reload or docker restart:
<img width="390" alt="image" src="https://github.com/h-quer/Slaanesh/assets/33106127/d932b2a1-3aed-4c23-9592-610937854d70">

Also since i updated today, i am getting this error in log: 
<img width="474" alt="image" src="https://github.com/h-quer/Slaanesh/assets/33106127/20152d03-245b-4a3b-bb57-7fe641bb20bd">

**Comment by h-quer** [comment]
The date parser of the import/export function wasn't working properly. I just implemented a fix, this should work with the newest version.
You might have to delete existing database files first, if they contain dates with the wrong data types.

**Comment by RyuuSlayer** [comment]
Works like a charm now, much appreciated!
